#WS CONFIGURATION if app is not available
host: http://localhost
port: 8181
ws_path: ws
#DAISY Pipeline app launch path (default to PATH lookup)
app_path: DAISY Pipeline
# ROBOT CONF
client_key: clientid
client_secret: supersecret
#debug
debug: false
starting: true
